### ISSUE TITLE
Code seems unfinished

### ISSUE THREAD

**Issue by luk-f-a** [leomartire/MVG-Moments#2]
hi @leomartire thanks for coding these formulas and sharing them. I tried to use the python version but noticed that it seems unfinished. Some parts are commented out with warnings that it must be tested.
I know this repo is from years ago, but I was wondering if you ever completed the code and maybe could upload it.

Thanks!

**Comment by camillemartire** [comment]
Hi @luk-f-a,

The repo is indeed several years old, but I just took a quick look at it.
If you are referring to the two warnings in CGMoms.py (lines 94 & 137 of commit #925bfb3), they were not critical and only due to the fact that I did not have SciPy available at the time. I've provided a few corrections, and everything should work fine now.
Please let me know if there is anything else, or if you find any other errors.

Cheers,

Léo

**Comment by luk-f-a** [comment]
Thanks @leomartire. I could use `CGMoms_Kan` but for `CGMoms` I didn't get the results I expected. Thanks to your reference to the original paper I could implement the formula. 
Again, thanks for sharing your code, if everyone did this research would be much easier!
